- en_name: BTC
  cn_name: 比特币
  fee: 0.002
- en_name: ETH
  cn_name: 以太坊
  fee: 0.002
- en_name: LTC
  cn_name: 莱特币
  fee: 0.005
- en_name: EOS
  cn_name: 柚子币
  fee: 0.002
- en_name: BCH
  cn_name: 比特现金
  fee: 0.002
- en_name: XRP
  cn_name: 瑞波币
  fee: 0.003
