- en_name: binance
  cn_name: 币安
  fee: 0.002
- en_name: neraex
  cn_name: 耐思
  fee: 0.005
- en_name: gateio
  cn_name: 比特儿
  fee: 0.002
- en_name: huobi
  cn_name: 火币
  fee: 0.002
- en_name: Bitfinex
  cn_name: B网
  fee: 0.002
- en_name: ZB
  cn_name: 中国比特币
  fee: 0.002
